[package]
name = "artimate"
version = "0.1.0"
edition = "2021"

[dependencies]
pixels = "0.14.0"
winit = {version = "0.29", features = ["rwh_05"]}
winit_input_helper = "0.15.0"

[dev-dependencies]
tiny-skia = "0.11.4"
wassily = { git = "https://github.com/jeffreyrosenbluth/wassily" }
