[package]
name = "artimate"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
pixels = "0.14.0"
png = "0.17.16"
winit = {version = "0.30.8", features = ["rwh_05"]}

[dev-dependencies]
tiny-skia = "0.11.4"
wassily = { git = "https://github.com/jeffreyrosenbluth/wassily" }
